language: node_js
node_js:
- "12"
cache:
  directories:
  - node_modules # NPM packages
  - /home/travis/.local/bin
install:
- yarn
script:
- yarn test
after_success:
branches:
  only:
  - production
  - master
  - ampstart-2.0
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
